"""Generate public, dependency-free portfolio pages. Run: python build.py."""
from pathlib import Path
import json
from html import escape as e

ROOT = Path(__file__).parent
DIST = ROOT / 'dist'
PROJECTS = json.loads((ROOT / 'content/projects.json').read_text(encoding='utf-8'))
BASE = 'https://lizonghan24-prog.github.io/'

def head(title, description, prefix='./', canonical=''):
    return f'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title><meta name="description" content="{e(description)}"><meta name="theme-color" content="#f5f6f2">
<link rel="canonical" href="{BASE}{canonical}"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{BASE}{canonical}">
<link rel="icon" href="{prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{prefix}styles.css"><script src="{prefix}script.js" defer></script></head><body>
<a class="skip" href="#main">跳转到正文</a>'''

def nav(prefix=''):
    return f'''<header class="site-header"><div class="wrap nav-inner"><a class="brand" href="{prefix or '#home'}" aria-label="李宗翰，首页"><span class="brand-mark">LZ<span>·</span></span><span>李宗翰<small>ZONGHAN LI</small></span></a><nav aria-label="主导航"><a href="{prefix}#projects">项目</a><a href="{prefix}#approach">工作方式</a><a href="{prefix}#about">关于</a></nav><a class="nav-github" href="https://github.com/lizonghan24-prog" target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true">↗</span><span class="sr-only">（新标签页）</span></a></div></header>'''

def footer(prefix=''):
    return f'''<footer class="wrap footer"><span>© <span data-year>2026</span> 李宗翰</span><span>EMBEDDED SYSTEMS · SOFTWARE · INTERACTION</span><a href="{prefix or '#home'}">回到首页 ↑</a></footer></body></html>'''

def diagram(kind):
    # Conceptual illustrations, not product photos, screenshots or measured traces.
    common = '<g fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'
    drawings = {
      'playdock': '<rect x="75" y="28" width="350" height="181" rx="9"/><path d="M75 58h350M165 58v151"/><circle cx="91" cy="43" r="2"/><circle cx="102" cy="43" r="2"/><path d="M89 80h49M89 98h33M89 116h39"/><rect x="184" y="77" width="222" height="112" rx="5"/><path d="M237 109h115c18 0 28 53 9 58-12 4-23-17-31-17h-69c-9 0-20 21-32 17-19-5-9-58 8-58Z"/><path d="M246 120v21m-10-10h20"/><circle cx="338" cy="124" r="3"/><circle cx="350" cy="137" r="3"/><path d="M204 219h94m-47-10v10"/>',
      'smart-glasses': '<path d="M91 92h130l16 18h28l15-18h128M91 92l-28-28h42M408 92l28-28h-42"/><rect x="103" y="101" width="119" height="72" rx="27"/><rect x="278" y="101" width="119" height="72" rx="27"/><path d="M222 126q28-24 56 0M116 119h20m-20 8h34M293 119h37m-37 8h48"/><path stroke-dasharray="3 7" d="M249 53v36m0 77v40"/><circle cx="249" cy="43" r="8"/><path d="M234 193h30m-24 7h18m-12 7h6"/>',
      'motor-lab': '<circle cx="133" cy="121" r="51"/><circle cx="133" cy="121" r="33"/><circle cx="133" cy="121" r="10"/><path d="M133 70V54m0 134v-16m-51-51H65m119 0h30"/><rect x="268" y="58" width="153" height="124" rx="6"/><path d="M284 155h120M287 80v75m-3-35h19l14-25 19 49 20-41 14 17h32"/><path stroke-dasharray="4 6" d="M215 121h48"/><path d="M124 121h18m-9-9v18"/>',
      'motion-platform': '<path d="M67 175h368M86 188h330"/><rect x="159" y="140" width="174" height="31" rx="5"/><circle cx="181" cy="175" r="13"/><circle cx="310" cy="175" r="13"/><path d="M218 140V99h61v41M247 99V76"/><circle cx="247" cy="59" r="24"/><circle cx="247" cy="59" r="9"/><path d="M100 126h35m-7-6 7 6-7 6m252-6h-35m7-6-7 6 7 6M306 67q18 8 17 26m-7-5 7 5 6-8"/>',
      'balancing-robot': '<rect x="204" y="47" width="94" height="73" rx="8"/><path d="M222 65h22m-22 8h38M219 120l-38 27 26 40m74-67 38 27-26 40"/><circle cx="208" cy="187" r="24"/><circle cx="292" cy="187" r="24"/><circle cx="208" cy="187" r="9"/><circle cx="292" cy="187" r="9"/><path stroke-dasharray="4 6" d="M250 28v188M131 217h238"/><path d="M151 97q-20 23-12 54m-8-8 8 8 4-10M350 97q20 23 12 54m8-8-8 8-4-10"/>',
      'gimbal': '<ellipse cx="252" cy="187" rx="70" ry="19"/><path d="M182 187v13c0 25 140 25 140 0v-13M250 168v-25M184 95v44h132V95"/><rect x="211" y="70" width="80" height="57" rx="8"/><circle cx="251" cy="98" r="19"/><circle cx="251" cy="98" r="10"/><path d="M176 57q73-47 148 0m-4-9 4 9-10-1M354 86q24 28 0 57m0-12v12h11"/><path stroke-dasharray="4 6" d="M251 26v31M123 98h72m111 0h63"/>',
      'agent-keypad': '<path d="M134 73h233l-23 119H111Z"/><path d="m111 192 14 16h233l9-16V73M344 192l14 16"/><path d="m153 91-6 35h75l7-35Zm97 0-7 35h75l7-35ZM143 139l-6 35h75l7-35Zm97 0-7 35h75l7-35Z"/><path d="m176 105 10 6-13 7m93-8h23m-20 5h14M166 152l10 10m2-10-14 10m98-4 7 7 14-13"/><path d="M185 57h88"/>'
    }
    return f'<svg class="project-illustration" viewBox="0 0 500 240" aria-hidden="true">{common}{drawings[kind]}</g></svg>'

def card(p):
    return f'''<article class="project-card" data-category="{p['category']}"><a class="project-link" href="./projects/{p['id']}.html"><div class="project-visual {p['theme']}"><div class="visual-label"><span>{e(p['english'])}</span><span>{p['number']} / 07</span></div>{diagram(p['id'])}<div class="visual-foot"><span class="diagram-caption">系统概念示意</span><span class="visual-arrow" aria-hidden="true">↗</span></div></div><div class="card-body"><div class="card-meta"><span>{p['categoryLabel']}</span><span class="status">{p['status']}</span></div><h3>{p['title']}</h3><p>{p['summary']}</p><div class="card-bottom"><div class="tags">{''.join(f'<span>{t}</span>' for t in p['tags'])}</div><span class="read-project">项目详解 <span aria-hidden="true">↗</span></span></div></div></a></article>'''

hero_art = '''<div class="system-panel" role="img" aria-label="系统工作流示意：输入与感知连接嵌入式控制，再连接执行机构和桌面软件"><div class="panel-label"><span>SYSTEM OVERVIEW</span><span class="panel-dot"></span></div><div class="system-diagram"><div class="signal-node input-node"><span>01 / INPUT</span><b>输入与感知</b><small>Sensor · Human input</small></div><div class="trace trace-top"></div><div class="core-node"><div class="core-top">EMBEDDED SYSTEM</div><div class="core-chip"><span>感知</span><i>→</i><strong>控制</strong><i>→</i><span>反馈</span></div><span class="core-caption">FIRMWARE + INTERFACE</span></div><div class="trace trace-left"></div><div class="trace trace-right"></div><div class="signal-node output-node"><span>02 / OUTPUT</span><b>运动与执行</b><small>Motor · Actuator</small></div><div class="signal-node desktop-node"><span>03 / INTERFACE</span><b>桌面与交互</b><small>Software · Workflow</small></div></div><div class="panel-footer"><span>从设备端，到用户端。</span><span>CONCEPT DIAGRAM ↗</span></div></div>'''

index = head('李宗翰 | 嵌入式系统与软硬件开发', '李宗翰的工程作品集：嵌入式系统、运动控制、低功耗设备与桌面软件。精选七个项目，记录系统设计、工程实现与迭代。') + nav()
index += f'''<main id="main"><section class="hero wrap" id="home"><div class="hero-copy"><p class="eyebrow"><span class="tiny-square"></span> ZONGHAN LI / ENGINEERING PORTFOLIO</p><p class="hero-intro">你好，我是李宗翰。</p><h1>让硬件与软件，<br><span>协同工作。</span></h1><p class="hero-description">专注嵌入式系统、运动控制与设备软件。<br>从底层通信到桌面交互，把功能连接成完整的系统。</p><div class="hero-actions"><a class="button" href="#projects">浏览精选项目 <span aria-hidden="true">↘</span></a><a class="quiet-link" href="#about">了解我的方向 <span aria-hidden="true">→</span></a></div></div>{hero_art}</section>
<div class="discipline-bar wrap"><span>固件与接口</span><span>运动控制</span><span>低功耗设备</span><span>桌面软件</span><span class="bar-index">SELECTED WORK / 2026</span></div>
<section class="projects-section wrap" id="projects" aria-labelledby="projects-title"><div class="section-heading"><div><p class="eyebrow">01 / SELECTED PROJECTS</p><h2 id="projects-title">用项目，说明能力。</h2></div><p>七个项目，连接设备、控制与交互。<br>每个项目都保留实现重点与当前进展。</p></div><div class="project-toolbar"><div class="filters" role="group" aria-label="按技术方向筛选项目" hidden><button class="filter active" data-filter="all" aria-pressed="true">全部 <span>07</span></button><button class="filter" data-filter="control" aria-pressed="false">运动控制 <span>04</span></button><button class="filter" data-filter="embedded" aria-pressed="false">嵌入式设备 <span>02</span></button><button class="filter" data-filter="software" aria-pressed="false">设备软件 <span>01</span></button></div><span class="result-count" role="status" aria-live="polite">显示 7 个项目</span></div><div class="project-grid">{''.join(card(p) for p in PROJECTS)}</div></section>
<section class="approach-section" id="approach" aria-labelledby="approach-title"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">02 / ENGINEERING APPROACH</p><h2 id="approach-title">关注功能，也关注系统。</h2></div><p>让模块之间的关系清晰，<br>让每一次迭代都有依据。</p></div><div class="approach-grid"><article><span class="step">01 — DEFINE</span><h3>先明确接口</h3><p>从设备输入、通信协议与运行状态入手，理清硬件、固件和软件之间的责任。</p></article><article><span class="step">02 — CONNECT</span><h3>打通完整链路</h3><p>把采集、控制、反馈和用户操作连接起来，在真实交互中发现模块之间的问题。</p></article><article><span class="step">03 — VERIFY</span><h3>留下验证依据</h3><p>通过日志、实验数据、回归记录和交付文档追踪变化，明确已实现的部分与后续工作。</p></article></div></div></section>
<section class="about-section wrap" id="about" aria-labelledby="about-title"><div><p class="eyebrow">03 / ABOUT</p><h2 id="about-title">在软硬件之间，<br>把问题往前推进。</h2></div><div class="about-copy"><p class="about-lead">我主要实践嵌入式开发、机器人电控与设备软件，喜欢处理从单个模块走向完整系统时出现的问题。</p><p>项目覆盖运动机构、低功耗可穿戴设备、桌面上位机与实体交互工具。我关注底层通信是否清晰、设备状态是否可见，以及功能能否在实际使用中连贯地工作。</p><div class="skill-lines"><div><span>嵌入式</span><p>C / STM32 / 外设与通信</p></div><div><span>设备软件</span><p>Python / Electron / 桌面交互</p></div><div><span>工程协作</span><p>SolidWorks / 系统联调 / 技术文档</p></div></div></div></section>
<section class="contact-section wrap" id="contact"><div><p class="eyebrow">LET’S BUILD SOMETHING</p><h2>从一个具体的问题，<br>开始交流。</h2><p>嵌入式设备 · 运动控制 · 桌面软件 · 软硬件协作</p></div><a class="button" href="https://github.com/lizonghan24-prog" target="_blank" rel="noopener noreferrer">在 GitHub 找到我 <span aria-hidden="true">↗</span><span class="sr-only">（新标签页）</span></a></section></main>'''
(DIST / 'index.html').write_text(index + footer(), encoding='utf-8')
(DIST / 'projects').mkdir(exist_ok=True)
for i, p in enumerate(PROJECTS):
    next_p = PROJECTS[(i+1) % len(PROJECTS)]
    html = head(p['title'] + ' | 李宗翰', p['summary'], '../', f"projects/{p['id']}.html") + nav('../index.html')
    html += f'''<main id="main" class="case-main wrap"><a class="back-link" href="../index.html#projects">← 返回项目列表</a><section class="case-hero"><p class="eyebrow">PROJECT {p['number']} / {e(p['english'])}</p><h1>{p['title']}</h1><p class="case-summary">{p['summary']}</p><div class="case-meta"><span>{p['categoryLabel']}</span><span class="status">{p['status']}</span><div class="tags">{''.join(f'<span>{t}</span>' for t in p['tags'])}</div></div></section><div class="case-visual {p['theme']}"><div class="case-illustration">{diagram(p['id'])}</div><div class="case-visual-copy"><span class="eyebrow">SYSTEM CONCEPT</span><p>{p['goal']}</p><small>系统概念示意 · 非产品实拍</small></div></div><div class="case-layout"><aside class="case-aside"><span class="eyebrow">IN THIS PROJECT</span><nav aria-label="项目页导航"><a href="#overview">项目概览</a><a href="#engineering">工程重点</a><a href="#delivery">产物与进展</a></nav></aside><div class="case-content"><section id="overview"><p class="eyebrow">01 / OVERVIEW</p><h2>连接哪些环节</h2><p>{p['context']}</p><ol class="flow">{''.join(f'<li><span>0{j+1}</span>{label}</li>' for j,label in enumerate(p['flow']))}</ol></section><section id="engineering"><p class="eyebrow">02 / ENGINEERING</p><h2>工程重点</h2><div class="focus-list">{''.join(f'<article><span>0{j+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>' for j,(title,body) in enumerate(p['focus']))}</div></section><section id="delivery"><p class="eyebrow">03 / PROGRESS</p><h2>产物与当前进展</h2><ul class="deliverables">{''.join(f'<li>{o}</li>' for o in p['outputs'])}</ul><div class="progress-note"><span>当前阶段</span><p>{p['boundary']}</p></div></section></div></div><a class="next-project" href="./{next_p['id']}.html"><span><small>NEXT PROJECT / 下一个项目</small><strong>{next_p['title']}</strong></span><span aria-hidden="true">↗</span></a></main>'''
    (DIST / 'projects' / f"{p['id']}.html").write_text(html + footer('../index.html'), encoding='utf-8')
(DIST / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + ''.join(f'<url><loc>{BASE}{path}</loc></url>' for path in [''] + [f"projects/{p['id']}.html" for p in PROJECTS]) + '</urlset>', encoding='utf-8')
(DIST / 'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: ' + BASE + 'sitemap.xml\n', encoding='utf-8')
print(f'Built home + {len(PROJECTS)} project pages.')
